/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CustomerRank } from './customer-rank';
import {
    CustomerRankFromJSON,
    CustomerRankFromJSONTyped,
    CustomerRankToJSON,
    CustomerRankToJSONTyped,
} from './customer-rank';

/**
 * 顧客登録リクエスト
 * @export
 * @interface CreateCustomerReq
 */
export interface CreateCustomerReq {
    /**
     * 
     * @type {CustomerRank}
     * @memberof CreateCustomerReq
     */
    rank?: CustomerRank;
    /**
     * 名前
     * @type {string}
     * @memberof CreateCustomerReq
     */
    name?: string;
    /**
     * 住所
     * @type {string}
     * @memberof CreateCustomerReq
     */
    address?: string;
}



/**
 * Check if a given object implements the CreateCustomerReq interface.
 */
export function instanceOfCreateCustomerReq(value: object): value is CreateCustomerReq {
    return true;
}

export function CreateCustomerReqFromJSON(json: any): CreateCustomerReq {
    return CreateCustomerReqFromJSONTyped(json, false);
}

export function CreateCustomerReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerReq {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'] == null ? undefined : CustomerRankFromJSON(json['rank']),
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function CreateCustomerReqToJSON(json: any): CreateCustomerReq {
    return CreateCustomerReqToJSONTyped(json, false);
}

export function CreateCustomerReqToJSONTyped(value?: CreateCustomerReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': CustomerRankToJSON(value['rank']),
        'name': value['name'],
        'address': value['address'],
    };
}

