/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 顧客ランク
 * @export
 */
export const CustomerRank = {
    A: 'A',
    B: 'B',
    C: 'C'
} as const;
export type CustomerRank = typeof CustomerRank[keyof typeof CustomerRank];


export function instanceOfCustomerRank(value: any): boolean {
    for (const key in CustomerRank) {
        if (Object.prototype.hasOwnProperty.call(CustomerRank, key)) {
            if (CustomerRank[key as keyof typeof CustomerRank] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CustomerRankFromJSON(json: any): CustomerRank {
    return CustomerRankFromJSONTyped(json, false);
}

export function CustomerRankFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerRank {
    return json as CustomerRank;
}

export function CustomerRankToJSON(value?: CustomerRank | null): any {
    return value as any;
}

export function CustomerRankToJSONTyped(value: any, ignoreDiscriminator: boolean): CustomerRank {
    return value as CustomerRank;
}

