/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CustomerRank } from './customer-rank';
import {
    CustomerRankFromJSON,
    CustomerRankFromJSONTyped,
    CustomerRankToJSON,
    CustomerRankToJSONTyped,
} from './customer-rank';

/**
 * 顧客
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * ID
     * @type {number}
     * @memberof Customer
     */
    id?: number;
    /**
     * 
     * @type {CustomerRank}
     * @memberof Customer
     */
    rank?: CustomerRank;
    /**
     * 名前
     * @type {string}
     * @memberof Customer
     */
    name?: string;
    /**
     * 住所
     * @type {string}
     * @memberof Customer
     */
    address?: string;
}



/**
 * Check if a given object implements the Customer interface.
 */
export function instanceOfCustomer(value: object): value is Customer {
    return true;
}

export function CustomerFromJSON(json: any): Customer {
    return CustomerFromJSONTyped(json, false);
}

export function CustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Customer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'rank': json['rank'] == null ? undefined : CustomerRankFromJSON(json['rank']),
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function CustomerToJSON(json: any): Customer {
    return CustomerToJSONTyped(json, false);
}

export function CustomerToJSONTyped(value?: Customer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rank': CustomerRankToJSON(value['rank']),
        'name': value['name'],
        'address': value['address'],
    };
}

