/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ErrorDetail } from './error-detail';
import {
    ErrorDetailFromJSON,
    ErrorDetailFromJSONTyped,
    ErrorDetailToJSON,
    ErrorDetailToJSONTyped,
} from './error-detail';

/**
 * エラーレスポンス
 * @export
 * @interface ErrorRes
 */
export interface ErrorRes {
    /**
     * 
     * @type {Array<ErrorDetail>}
     * @memberof ErrorRes
     */
    id: Array<ErrorDetail>;
}

/**
 * Check if a given object implements the ErrorRes interface.
 */
export function instanceOfErrorRes(value: object): value is ErrorRes {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ErrorResFromJSON(json: any): ErrorRes {
    return ErrorResFromJSONTyped(json, false);
}

export function ErrorResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorRes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': ((json['id'] as Array<any>).map(ErrorDetailFromJSON)),
    };
}

export function ErrorResToJSON(json: any): ErrorRes {
    return ErrorResToJSONTyped(json, false);
}

export function ErrorResToJSONTyped(value?: ErrorRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': ((value['id'] as Array<any>).map(ErrorDetailToJSON)),
    };
}

