/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * エラー詳細
 * @export
 * @interface ErrorDetail
 */
export interface ErrorDetail {
    /**
     * メッセージID
     * @type {string}
     * @memberof ErrorDetail
     */
    messageId?: string;
    /**
     * 分類
     * @type {string}
     * @memberof ErrorDetail
     */
    category?: ErrorDetailCategory;
    /**
     * メッセージ
     * @type {string}
     * @memberof ErrorDetail
     */
    message?: string;
}


/**
 * @export
 */
export const ErrorDetailCategory = {
    Info: 'info',
    Warn: 'warn',
    Error: 'error'
} as const;
export type ErrorDetailCategory = typeof ErrorDetailCategory[keyof typeof ErrorDetailCategory];


/**
 * Check if a given object implements the ErrorDetail interface.
 */
export function instanceOfErrorDetail(value: object): value is ErrorDetail {
    return true;
}

export function ErrorDetailFromJSON(json: any): ErrorDetail {
    return ErrorDetailFromJSONTyped(json, false);
}

export function ErrorDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
        'category': json['category'] == null ? undefined : json['category'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ErrorDetailToJSON(json: any): ErrorDetail {
    return ErrorDetailToJSONTyped(json, false);
}

export function ErrorDetailToJSONTyped(value?: ErrorDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
        'category': value['category'],
        'message': value['message'],
    };
}

