/* tslint:disable */
/* eslint-disable */
/**
 * customer-api
 * customer api example
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yz-sample@sample.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CustomerRank } from './customer-rank';
import {
    CustomerRankFromJSON,
    CustomerRankFromJSONTyped,
    CustomerRankToJSON,
    CustomerRankToJSONTyped,
} from './customer-rank';

/**
 * 顧客検索条件
 * @export
 * @interface SearchCustomerCondition
 */
export interface SearchCustomerCondition {
    /**
     * 
     * @type {CustomerRank}
     * @memberof SearchCustomerCondition
     */
    id?: CustomerRank;
}



/**
 * Check if a given object implements the SearchCustomerCondition interface.
 */
export function instanceOfSearchCustomerCondition(value: object): value is SearchCustomerCondition {
    return true;
}

export function SearchCustomerConditionFromJSON(json: any): SearchCustomerCondition {
    return SearchCustomerConditionFromJSONTyped(json, false);
}

export function SearchCustomerConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCustomerCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : CustomerRankFromJSON(json['id']),
    };
}

export function SearchCustomerConditionToJSON(json: any): SearchCustomerCondition {
    return SearchCustomerConditionToJSONTyped(json, false);
}

export function SearchCustomerConditionToJSONTyped(value?: SearchCustomerCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': CustomerRankToJSON(value['id']),
    };
}

