server:
  port: 8081
  servlet:
    context-path: /order-service
spring:
  application:
    name: order
  datasource:
      driver-class-name: org.h2.Driver
      # use memory
      url: jdbc:h2:mem:sampleDb
      # use file
      # url: jdbd:h2:./h2db/sampleDb
      username: sa
      password:
  jpa:
      open-in-view: false
      show-sql: true
      properties:
          hibernate:
              enable_lazy_load_no_trans: true
