GET http://localhost:3000/customers

## dev
### public ip
GET https://43.206.237.239:8082/customers HTTP/1.1
### public DNS
GET https://ec2-43-206-237-239.ap-northeast-1.compute.amazonaws.com:8082/customers HTTP/1.1
### private ip
GET https://10.0.0.176:8082/customers HTTP/1.1
### private DNS
GET https://ip-10-0-0-176.ap-northeast-1.compute.internal:8082/customers HTTP/1.1

