# customer-serviceを開発環境にデプロイ
name: Deploy to AWS(customer-service:dev)

on:
  workflow_dispatch: 
  push:
    branches:
      - 'develop/**'
    paths: 
      - 'customer/**'

jobs:
  # デプロイ(デプロイ先：AWS)
  deploy:
    uses: ./.github/workflows/deploy-aws_dev.yaml
    secrets: inherit 
    with:
      app-name: customer
      app-version: 0.0.1
      aws-region: ap-northeast-1
      aws-ecr-repository-name: consider-cicd
      ecs-cluster-name: consider-cicd-ecs
      ecs-service-name: consider-cicd-ecs-service_customer-service
      ecs-task-name: consider-cicd-ecs-task-customer
      env-variables: |
        {"name": "PORT", "value": "8082"}, 
        {"name": "TEST_ENV", "value": "production"}
