# # React+TypeScriptアプリケーションのビルド
# ## 前提とする言語、環境など
# * Node.js
# * (React)
# * (TypeScript)
# * lint: esLint
# * test: jest
# * build: vite
# * ※「xxx: yyy」：yyyをベースとして実装していますが、xxxコマンドで実行できればよいので他のモノでも代替可。
# * ※(yyy)：yyyをベースとして実装していますが、当ワークフローはこれに特化した処理は含んでいないため、他のモノでも代替可。
# ## 備考
# * 初稿時点では、処理内容はTypeScript Applicationと同じですが、UI特有の処理(ヴィジュアルテストなど)が追加される可能性を考慮して、別ファイルで作成。
name: Build React Application

on:
  workflow_call:
    inputs:
      app-name:
        description: アプリケーション名
        required: true
        type: string
      app-version:
        description: アプリケーションバージョン
        required: true
        type: string
      work-directory:
        description: 作業ディレクトリ（アプリのルートフォルダ）
        required: true
        type: string
      dist-directory:
        description: ビルドリソースの生成されるフォルダー
        required: false
        type: string
        default: dist
      node-version:
        description: Nodeのバージョン
        required: true
        type: string
      test-report-cache-key:
        description: テストレポートのキャッシュキー名
        required: true
        type: string
      build-artifacts-cache-key:
        description: ビルドしたアーティファクトのキャッシュキー名
        required: true
        type: string
      pr-comment-cache-key:
        description: PRコメントファイルのキャッシュキー名
        required: true
        type: string
      pr-comment-folder-name:
        description: PRへのフィードバックコメントファイルの格納先フォルダー名
        required: true
        type: string
      pr-comment-file-name:
        description: PRへのフィードバックコメントファイル名
        required: true
        type: string
      is-publish:
        description: Jar,イメージの公開有無(true:公開する、false:公開しない)
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.work-directory }}
    env:
      test-report-directory_built: test-result/reports
      test-report-directory_for_transport-to-pages: pages/${{ inputs.app-name }}/test-result/reports
      test-report-directory_for_pages: ${{ inputs.app-name }}/test-result/reports
      style-check-tool-name: lint
    steps:
      # 実行環境セットアップ
      ## コードをチェックアウト
      - name: checkout source
        uses: actions/checkout@v3
      ## Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm' # npmキャッシュを有効化
          cache-dependency-path: ${{ inputs.work-directory }}/package-lock.json
      ## 依存ライブラリのインストール
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev jest-html-reporters
      ## 後続プロセスで使用するディレクトリの初期化
      - run: |
          mkdir -p ${{ inputs.pr-comment-folder-name }}
          mkdir -p ${{ env.test-report-directory_for_transport-to-pages }}
      ## PRコメントダウンロード
      ## * PRコメントがある場合、加筆するためダウンロード。
      ## * ファイルが存在しなくてもエラーにしない
      - name: Download pr-comment
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.pr-comment-cache-key }}
          path: ${{ inputs.work-directory }}/${{ inputs.pr-comment-folder-name }}
        continue-on-error: true
      ## PRコメント
      - name: PR comment
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "
            * ワークフローごとに保存しているテスト結果は[こちら]($ARTIFACT_URL)　※GitHubの設定期間保持されます（デフォルト：90日）  
            " >> ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }}

      # 静的解析（Lint）
      - name: Run Lint
        run: npm run lint:ci
        continue-on-error: true #Lintエラーは後続でチェックするためスキップ
      ## 静的解析レポートのアップロード（レポート公開向けの一時保存）
      - name: move static analysis report
        run: |
          mv ${{ env.test-report-directory_built }}/${{ env.style-check-tool-name }} ${{ env.test-report-directory_for_transport-to-pages }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test-report-cache-key }}
          path: ${{ inputs.work-directory }}/pages
      ## PRコメント
      - name: PR comment
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          PAGES_URL="https://${{ github.repository_owner }}.github.io/$REPO_NAME"
          TEST_REPORT_ROOT_URL="$PAGES_URL/${{ env.test-report-directory_for_pages }}"

          LINT_REPORT_URL="$TEST_REPORT_ROOT_URL/${{ env.style-check-tool-name }}/index.html"
          
          echo "
            ## 静的解析結果のフィードバック  
            * コードスタイルレポートのプレビューは[こちら]($LINT_REPORT_URL)　※ワークフローが動くと上書きされます  
            " >> ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }}
      ## PRコメントアップロード
      - name: Upload pr-comment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.pr-comment-cache-key }}
          path: ${{ inputs.work-directory }}/${{ inputs.pr-comment-folder-name }}
          overwrite: true
      ## 静的解析結果の解析
      ## * ESLintでWaningまたはErrorが検出されていた場合、ワークフローを中断する
      - run: tree # debug
      - name: Check for Warnings and Errors
        run: |
          if grep -q -E "error|warnings" test-result/reports/lint/index.html; then
            exit 1
          fi

      # テスト
      - name: Run Unit Tests
        run: npm run test:ci
      ## テストレポートのアップロード（レポート公開向けの一時保存）
      - name: move test report
        run: mv test-result/* ${{ env.test-report-directory_for_transport-to-pages }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test-report-cache-key }}
          path: ${{ inputs.work-directory }}/pages
      - name: PR FB
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          PAGES_URL="https://${{ github.repository_owner }}.github.io/$REPO_NAME"
          TEST_REPORT_ROOT_URL="$PAGES_URL/${{ inputs.app-name }}/reports/test-report"

          COVERAGE_URL="$TEST_REPORT_ROOT_URL/coverage/lcov-report/index.html"
          TEST_REPORT_URL="$TEST_REPORT_ROOT_URL/rest-report/index.html"

          echo "
            ## テスト結果のフィードバック
            * カバレッジレポートのプレビューは[こちら]($COVERAGE_URL)　※ワークフローが動くと上書きされます
            * テスト結果レポートのプレビューは[こちら]($TEST_REPORT_URL)　※ワークフローが動くと上書きされます
            " >> ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }}
  
      # ビルド
      - name: Build App
        run: npm run build
      ## アーティファクトのアップロード（イメージビルド向けの一時保存）
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build-artifacts-cache-key }}
          path: ${{ inputs.work-directory }}/${{ inputs.dist-directory }}

      # アーティファクト公開（公開先：GitHub Packages）
      - name: Publish artifact to GitHub Packages
        if: inputs.is-publish
        id: publish-artifact-to-packages
        run: |
          npm config set @${{ github.repository_owner }}:registry=https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm publish || echo "Publish failed, skipping"
        continue-on-error: true #リポジトリがimmutableの場合、同一バージョンのpushはできないため、エラー無視
      ## アーティファクト公開コールバック
      - name: callback to console
        if: steps.publish-artifact-to-packages.outcome == 'failure'
        run: echo 同一バージョンのパッケージはプッシュできません。バージョンを変えるか、同一バージョンのパッケージを削除してリトライしてください。
      - name: callback to PR
        if: ${{ steps.publish-artifact-to-packages.outcome == 'failure' && github.event.pull_request.number != '' }}
        run: |
          echo "
            ## パッケージプッシュのフィードバック  
            * 同一バージョンのパッケージはプッシュできません。バージョンを変えるか、同一バージョンのパッケージを削除してリトライしてください。
            " >> ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }}

      # PRコメントアップロード
      - name: Upload pr-comment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.pr-comment-cache-key }}
          path: ${{ inputs.work-directory }}/${{ inputs.pr-comment-folder-name }}
          overwrite: true
