# # PRへのフィードバック
# * PRがトリガーではない場合、フィードバック先がないため、何もせずに終了します
# ## 前提条件
# * PRへのフィードバック事項を下記の条件でファイルにまとめてアップロードしていること。
#   * key: inputs.pr-comment-cached-keyに設定してください
#   * file name: pr-comment.md固定
name: PR feedback

on:
  workflow_call:
      inputs:
        pr-comment-cached-key:
          description: キャッシュしたPRコメントファイルのキー名
          required: true
          type: string
        pr-comment-folder-name:
          description: PRへのフィードバックコメントファイルの格納先フォルダー名
          required: true
          type: string
        pr-comment-file-name:
          description: PRへのフィードバックコメントファイル名
          required: true
          type: string
                
jobs:
  pr-feedback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    ## コードをチェックアウト
    - name: checkout source
      uses: actions/checkout@v5
    # PRコメントダウンロード（事前にアップロードしていたファイルを取得）
    - name: download pr-comment
      id: download-pr-comment
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.pr-comment-cached-key }}
        path: ${{ inputs.pr-comment-folder-name }}
      continue-on-error: true

    # PRコメント
    - name: PR comment
      # PRにフィードバックするにはフィードバック先が必要なのでPR番号を持っていない場合はスキップ
      # フィードバックコメントのダウンロードに失敗した場合も同様にスキップ
      if: github.event.pull_request.number != '' && steps.download-pr-comment.outcome != 'failure'
      # Tips: botが1回もコメントしてない場合、--edit-lastを付けるとエラーになる
      # botのコメントが1つもない場合、「no comments found for current user」となってしまう。
      # それに対処するため、「||」以降に通常のコメントコマンドも併記している。
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }} --edit-last || gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ inputs.pr-comment-folder-name }}/${{ inputs.pr-comment-file-name }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # memo: Enterprise planの場合、下記のパラメータが必要になるらしい
        # GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GH_HOST: your-host.com 
