# java21, maven
name: CI/CD java application

on:
  push:
    # 一旦、mainブランチへのpushをトリガーにして実行
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # コードをチェックアウト
      - uses: actions/checkout@v3
      # JDK 17 をセットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      # Mavanリポジトリのキャッシュ
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # GitHub Packagesへの認証設定追加
      - name: Generate Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
      # Maven でビルドし、jar ファイルを生成
      - name: Build with Maven
        run: |
          cd order
          mvn clean install
      - name: Publish to GitHub Packages
        run: |
          cd order
          mvn deploy -DskipTests -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Dockerイメージをビルド
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/consider-cicd:${{ github.sha }} .
