# # TypeScriptアプリケーションのビルド
# ## 前提とする言語など
# * TypeScript
# * Node.js
name: CI/CD TS Application

env:
  APP_NAME: customer-service
  APP_VERSION: 0.0.1
  AWS_REGION: ap-northeast-1
  WORK_DIRECTORY: customer/customer-service
  DIST_DIRECTORY: dist # ビルドリソースの生成されるフォルダー（ex. Node:dist）
  TEST_REPORT_DIRECTORY: test-result #WORK_DIRECTORYから見たパス
  NODE_VERSION: 20 # 使用するNode.jsのバージョン

on:
  workflow_dispatch: 
  push:
    branches: 
      - 'feature/**'
      - 'topic/**'
    paths: 
      - 'customer/**'
      - '.github/workflows/**' # ワークフロー自体の更新もトリガー

jobs:
  build:
    uses: ./.github/workflows/build-ts-app.yaml
    with:
      app-name: customer-service
      app-version: 0.0.1
      work-directory: customer/customer-service
      dist-directory: dist
      node-version: 20
      build-artifacts-cache-key: artifact-dist-customer-service
      is-publish: true
  # イメージビルド
  build-image:
    needs: build
    uses: ./.github/workflows/build-image.yaml
    with:
      app-name: customer-service
      app-version: 0.0.1
      work-directory: customer/customer-service
      dist-directory: /dist
      build-artifacts-cache-key: artifact-dist-customer-service
      is-publish: true
  # テストレポートを公開
  publish-test-result:
    needs: build-image
    uses: ./.github/workflows/publish-report.yaml
    with:
      app-name: customer-service
    # runs-on: ubuntu-latest
    # needs: build-image
    # permissions:
    #   pages: write
    #   id-token: write
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    # steps:
    # - name: init
    #   run: mkdir pages
    # # レポートダウンロード（事前にアップロードしていたレポートを取得）
    # - name: download test report
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: test-report_${{ env.APP_NAME }}
    #     path: pages
    # - name: download image scan report
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: image-scan-report_${{ env.APP_NAME }}
    #     path: pages
    # # レポート公開(公開先：GitHub Pages)
    # - name: upload
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: pages
    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v4
  # デプロイ(デプロイ先：AWS)
  deploy:
    needs: build-image
    uses: ./.github/workflows/deploy-aws_dev.yaml
    secrets: inherit
    with:
      app-name: customer-service
      app-version: 0.0.1
      aws-region: ap-northeast-1
      aws-ecr-repository-name: consider-cicd
      ecs-cluster-name: consider-cicd-ecs
      ecs-service-name: consider-cicd-ecs-service_customer-service
      ecs-task-name: consider-cicd-ecs-task-customer-service
      env-variables: |
        {"name": "PORT", "value": "8082"}, 
        {"name": "TEST_ENV", "value": "dev"}
