name: Publish Reports
on:
  workflow_run:
    workflows:
      - "Frontend Build"
      - "Backend (TS) Build"
      - "Backend (Java) Build"
    types:
      - completed

jobs:
  publish-reports:
    runs-on: ubuntu-latest
    steps:
      # checkout 
      - name: Check out code
        uses: actions/checkout@v3
      # download report(frontend)
      - name: Download frontend reports
        uses: actions/download-artifact@v3
        with:
          name: frontend-report
      # download report(backend ts)
      - name: Download backend TS reports
        uses: actions/download-artifact@v3
        with:
          name: backend-ts-report

      - name: Download backend Java reports
        uses: actions/download-artifact@v3
        with:
          name: backend-java-report

      - name: Prepare reports for Pages
        run: |
          mkdir -p public/reports
          mv frontend-report/* public/reports/frontend/
          mv backend-ts-report/* public/reports/backend-ts/
          mv backend-java-report/* public/reports/backend-java/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
