# # Reactアプリケーションのビルド
# ## 前提とする言語、環境など
# * Node.js
# * (React)
# * (TypeScript)
# * lint: esLint
# * test: jest
# * build: vite
# * ※「xxx: yyy」：yyyをベースとして実装していますが、xxxコマンドで実行できればよいので他のモノでも代替可。
# * ※(yyy)：yyyをベースとして実装していますが、当ワークフローはこれに特化した処理は含んでいないため、他のモノでも代替可。
name: CI React Application

on:
  workflow_dispatch: 
  pull_request:
    branches: 
      - 'develop/**'
    paths: 
      - 'order-ui/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  # ワークフロー設定のロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: dev
      config-file-directory: order-ui
  # ビルド
  build:
    needs: workflow-config
    uses: ./.github/workflows/_build-react-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      node-version: ${{ needs.workflow-config.outputs.node-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      pr-comment-cache-key: ${{ needs.workflow-config.outputs.pr-comment-cache-key}}
      is-publish: false
  # テストレポートを公開
  publish-test-result:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/_publish-report.yaml
    with:
      app-name: order-ui
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
  # PRフィードバック
  pr-feedback:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/_pr-fb.yaml
    with:
      pr-comment-cached-key: ${{ needs.workflow-config.outputs.pr-comment-cache-key }}
