# # TypeScriptアプリケーションのビルド
# ## 前提とする言語など
# * TypeScript
# * Node.js
name: CI TS Application

env:
  APP_NAME: customer-service
  APP_VERSION: 0.0.1
  AWS_REGION: ap-northeast-1
  WORK_DIRECTORY: customer/customer-service
  DIST_DIRECTORY: dist # ビルドリソースの生成されるフォルダー（ex. Node:dist）
  TEST_REPORT_DIRECTORY: test-result #WORK_DIRECTORYから見たパス
  NODE_VERSION: 20 # 使用するNode.jsのバージョン

on:
  workflow_dispatch: 
  pull_request:
    branches: 
      - 'feature/**'
      - 'topic/**'
    paths: 
      - 'customer/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  build:
    uses: ./.github/workflows/build-ts-app.yaml
    with:
      app-name: customer-service
      app-version: 0.0.1
      work-directory: customer/customer-service
      dist-directory: dist
      node-version: 20
      test-report-cache-key: test-report_customer-service
      build-artifacts-cache-key: artifact-dist-customer-service
      is-publish: false
  # イメージビルド
  build-image:
    needs: build
    uses: ./.github/workflows/build-image.yaml
    with:
      app-name: customer-service
      app-version: 0.0.1
      work-directory: customer/customer-service
      dist-directory: /dist
      build-artifacts-cache-key: artifact-dist-customer-service
      scan-report-cache-key: image-scan-report_customer-service
      is-publish: false
  # テストレポートを公開
  publish-test-result:
    needs: build-image
    uses: ./.github/workflows/publish-report.yaml
    with:
      app-name: customer-service
      test-report-cached-key: test-report_customer-service
      scan-report-cached-key: image-scan-report_customer-service
