# # TypeScriptアプリケーションのビルド
# ## 前提とする言語など
# * TypeScript
# * Node.js
name: CI/CD TS Application

on:
  workflow_dispatch: 
  push:
    branches: 
      - 'develop/**'
    paths: 
      - 'customer/**'

jobs:
  # ワークフローの設定ロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: dev
      config-file-directory: customer/customer-service
  # ビルド
  build:
    uses: ./.github/workflows/_build-ts-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      node-version: ${{ needs.workflow-config.outputs.node-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      is-publish: true
  # イメージビルド
  build-image:
    needs: build
    uses: ./.github/workflows/_build-image.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      build-artifacts-cached-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      scan-report-cache-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
      is-publish: true
  # テストレポートを公開
  publish-test-result:
    needs: build-image
    uses: ./.github/workflows/_publish-report.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      scan-report-cached-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
  # デプロイ
  deploy:
    needs: build-image
    uses: ./.github/workflows/_deploy-dev-aws-backend.yaml
    secrets: inherit
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      aws-region: ${{ needs.workflow-config.outputs.aws-region}}
      aws-ecr-repository-name: ${{ needs.workflow-config.outputs.aws-ecr-repository-name}}
      ecs-cluster-name: ${{ needs.workflow-config.outputs.ecs-cluster-name}}
      ecs-service-name: ${{ needs.workflow-config.outputs.ecs-service-name}}
      ecs-task-name: ${{ needs.workflow-config.outputs.ecs-task-name}}
      env-variables: ${{ needs.workflow-config.outputs.env-variables}}
