# # Javaアプリケーションのビルド
# ## 前提とする言語、環境など
# * Java
# * Maven
name: CI/CD Java Application

on:
  workflow_dispatch: #手動実行
  push:
    branches: 
      - 'develop/**'
    paths: 
      - 'order/**'

jobs:
  # ワークフロー設定のロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: dev
      config-file-directory: order
  # ビルド
  build:
    needs: workflow-config
    uses: ./.github/workflows/_build-java-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      java-version: ${{ needs.workflow-config.outputs.java-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      pr-comment-folder-name: ${{ needs.workflow-config.outputs.pr-comment-folder-name }}
      pr-comment-file-name: ${{ needs.workflow-config.outputs.pr-comment-file-name }}
      is-publish: true
  # イメージビルド
  build-image:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/_build-image.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      build-artifacts-cached-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      scan-report-cache-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
      current-pr-comment-cache-key: ${{ needs.build.outputs.new-pr-comment-cache-key }}
      pr-comment-folder-name: ${{ needs.workflow-config.outputs.pr-comment-folder-name }}
      pr-comment-file-name: ${{ needs.workflow-config.outputs.pr-comment-file-name }}
      is-publish: true
  # テストレポートを公開
  publish-test-result:
    needs: 
      - workflow-config
      - build-image
    uses: ./.github/workflows/_publish-report.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      scan-report-cached-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
  # デプロイ
  deploy:
    needs:
      - workflow-config 
      - build-image
    uses: ./.github/workflows/_deploy-dev-aws-backend.yaml
    # Tips：自身で設定したsecretを別ファイルから参照するには？
    # 別ファイルにしたワークフローはスコープの問題でsecretの参照に失敗します。
    # inheritをつけることで呼び出し先にSecretが引き継がれるので、呼び出し先でも参照することができます。
    secrets: inherit 
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      aws-region: ${{ needs.workflow-config.outputs.aws-region}}
      aws-ecr-repository-name: ${{ needs.workflow-config.outputs.aws-ecr-repository-name}}
      ecs-cluster-name: ${{ needs.workflow-config.outputs.ecs-cluster-name}}
      ecs-service-name: ${{ needs.workflow-config.outputs.ecs-service-name}}
      ecs-task-name: ${{ needs.workflow-config.outputs.ecs-task-name}}
      env-variables: ${{ needs.workflow-config.outputs.env-variables}}
  # PRフィードバック
  pr-feedback:
    needs: 
      - workflow-config
      - build-image
      - deploy
    uses: ./.github/workflows/_pr-fb.yaml
    with:
      pr-comment-cached-key: ${{ needs.build.outputs.new-pr-comment-cache-key }}
      pr-comment-folder-name: ${{ needs.workflow-config.outputs.pr-comment-folder-name }}
      pr-comment-file-name: ${{ needs.workflow-config.outputs.pr-comment-file-name }}
