# # Reactアプリケーションのビルド
# ## 前提とする言語など
# * React
# * TypeScript
# * Node.js
# * Vite
name: CI React Application

on:
  workflow_dispatch: 
  pull_request:
    branches: 
      - 'develop/**'
    paths: 
      - 'order-ui/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  # ワークフローの設定ロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: dev
      config-file-directory: order-ui
  # ビルド
  build:
    needs: workflow-config
    uses: ./.github/workflows/_build-react-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      node-version: ${{ needs.workflow-config.outputs.node-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      is-publish: false
  # テストレポートを公開
  publish-test-result:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/_publish-report.yaml
    with:
      app-name: order-ui
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
