# # Reactアプリケーションのビルド
# ## 前提とする言語など
# * React
# * TypeScript
# * Node.js
# * Vite
name: CI/CD React Application

on:
  workflow_dispatch: 
  push:
    branches: 
      - 'develop/**'
    paths: 
      - 'order-ui/**'

jobs:
  # ワークフローの設定ロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: dev
      config-file-directory: order-ui
  # ビルド
  build:
    needs: workflow-config
    uses: ./.github/workflows/_build-react-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      node-version: ${{ needs.workflow-config.outputs.node-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}_dev
      is-publish: true
  # テストレポートを公開
  publish-test-result:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/_publish-report.yaml
    with:
      app-name: order-ui
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
  # デプロイ
  deploy:
    needs:
      - workflow-config 
      - build
    uses: ./.github/workflows/_deploy-dev-aws-frontend.yaml
    secrets: inherit
    with:
      aws-region: ${{ needs.workflow-config.outputs.aws-region}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      build-artifacts-cached-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}_dev
      s3-bucket-name: ${{ needs.workflow-config.outputs.s3-bucket-name}}
      distribution-id: ${{ needs.workflow-config.outputs.distribution-id}}

