# # Javaアプリケーションのビルド
# ## 前提とする言語など
# * Java
# * Maven
name: CI Java Application

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - 'develop/**'
    paths: 
      - 'order/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  # ワークフローの設定ロード
  workflow-config:
    uses: ./.github/workflows/load-config.yaml
    with:
      profile: dev
      config-file-directory: order
  # ビルド
  build:
    needs: workflow-config
    uses: ./.github/workflows/build-java-app.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      java-version: ${{ needs.workflow-config.outputs.java-version}}
      test-report-cache-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      build-artifacts-cache-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      is-publish: false
  # イメージビルド
  build-image:
    needs: 
      - workflow-config
      - build
    uses: ./.github/workflows/build-image.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      work-directory: ${{ needs.workflow-config.outputs.work-directory}}
      dist-directory: ${{ needs.workflow-config.outputs.dist-directory}}
      build-artifacts-cached-key: ${{ needs.workflow-config.outputs.build-artifacts-cache-key}}
      scan-report-cache-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
      is-publish: false
  # テストレポートを公開
  publish-test-result:
    needs: 
      - workflow-config
      - build-image
    uses: ./.github/workflows/publish-report.yaml
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      test-report-cached-key: ${{ needs.workflow-config.outputs.test-report-cache-key}}
      scan-report-cached-key: ${{ needs.workflow-config.outputs.scan-report-cache-key}}
