# # Javaアプリケーションのビルド
# ## 前提とする言語など
# * Java
# * Maven
name: build Java Application

env:
  APP_NAME: order # アプリケーション名
  APP_VERSION: 0.0.1 # アプリケーションバージョン
  AWS_REGION: ap-northeast-1 # AWSリージョン
  WORK_DIRECTORY: order # 作業ディレクトリ
  DIST_DIRECTORY: target # ビルドリソースの生成されるフォルダー
  JAVA_VERSION: 21 # 使用するJavaのバージョン

on:
  workflow_dispatch:
  push:
    branches: 
      - 'feature/**'
      - 'topic/**'
    paths: 
      - 'order/**'

jobs:
  # ビルド
  build:
    uses: ./.github/workflows/build-java-app.yaml
    with:
      app-name: order
      app-version: 0.0.1
      work-directory: order
      dist-directory: target
      java-version: 21
      test-report-cache-key: test-report_order
      build-artifacts-cache-key: artifact-dist-order
      is-publish: false
  # イメージビルド
  build-image:
    needs: build
    uses: ./.github/workflows/build-image.yaml
    with:
      app-name: order
      app-version: 0.0.1
      work-directory: order
      dist-directory: /target
      build-artifacts-cached-key: artifact-dist-order
      scan-report-cache-key: image-scan-report_order
      is-publish: false
  # テストレポートを公開
  publish-test-result:
    needs: build-image
    uses: ./.github/workflows/publish-report.yaml
    with:
      app-name: order
      test-report-cached-key: test-report_order
      scan-report-cached-key: image-scan-report_order
