# order-serviceをステージング環境にデプロイ
name: Deploy to AWS(order-service:staging)

on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
    paths: 
      - 'order/**'

jobs:
  # ワークフローの設定ロード
  workflow-config:
    uses: ./.github/workflows/_load-config.yaml
    with:
      profile: stage
      config-file-directory: order
  # デプロイ(デプロイ先：AWS)
  deploy:
    needs: workflow-config
    uses: ./.github/workflows/_deploy-stage-aws-backend.yaml
    secrets: inherit 
    with:
      app-name: ${{ needs.workflow-config.outputs.app-name}}
      app-version: ${{ needs.workflow-config.outputs.app-version}}
      aws-region: ${{ needs.workflow-config.outputs.aws-region}}
      aws-ecr-repository-name: ${{ needs.workflow-config.outputs.aws-ecr-repository-name}}
      ecs-cluster-name: ${{ needs.workflow-config.outputs.ecs-cluster-name}}
      ecs-service-name: ${{ needs.workflow-config.outputs.ecs-service-name}}
      ecs-task-name: ${{ needs.workflow-config.outputs.ecs-task-name}}
      env-variables: ${{ needs.workflow-config.outputs.env-variables}}
